name: Update GitHub Activity Feed

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Activity Feed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update README.md
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          README_FILE: README.md
          COMMIT_MSG: "⚡ Update GitHub Activity Feed (pt-BR)"
          MAX_LINES: 5

      - name: Git Pull
        run: git pull origin main
        continue-on-error: true
        
      - name: Update README_EN.md
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          README_FILE: README_EN.md
          COMMIT_MSG: "⚡ Update GitHub Activity Feed (en-US)"
          MAX_LINES: 5
